DROP TABLE IF EXISTS BOTTLES;
DROP TABLE IF EXISTS USERS;

CREATE TABLE BOTTLES(
   ID INTEGER PRIMARY KEY   AUTOINCREMENT,
   BRAND			TEXT    NOT NULL,
   PRICE			INTEGER	NOT NULL,
   VOLUME			INTEGER	NOT NULL,
   NUMBER			INTEGER
);

INSERT INTO BOTTLES (BRAND, PRICE, VOLUME, NUMBER)
VALUES ('1664', 100, 75, 5);


CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY   AUTOINCREMENT,
    USERNAME           TEXT    NOT NULL,
    PASSWORD        TEXT    NOT NULL,
	PERMISSION		INTEGER		
);

INSERT INTO USERS (USERNAME, PASSWORD, PERMISSION)
VALUES ('admin', 'admin123', 0);